### ISSUE TITLE
Initial comments.

### ISSUE THREAD

**Issue by jzmaddock** [CPPAlliance/drone-ci#1]
First off, thanks ever so much for doing this, Travis has become terribly backed up - unsurprisingly so IMO - and this looks like a great step forward.

I've just filed a test PR against Boost.Config and the results look good and integration is working well: https://drone.cpp.al/boostorg/config/3/31/2

I have some general questions and suggestions:

* I don't see anywhere what the OS is, OK Linux, x64, but there can be differences between distros.  Ditto for OS X release.
* Is there a way to add a status badge to the projects readme?
* What compilers are currently available on the server?  I notice that Config really should be testing gcc/clang-10 for example.
* Currently available CI has a preponderance of x64 testing.  For numerical software (Math, Multiprecision, Random) this has been bugging me as a big hole in our current testing.  Is this a gap you might be prepared to try and fill?
* Commercial compilers such as Intel C++ are unusable on Travis despite having a free licence for open source projects, is this something you might be able to make available?  There are others of course: Oracle on Solaris, IBM on AIX/Linux and so on.
* Maintaining separate CI scripts for each Boost library is a pain, and results in somewhat patchy CI testing, I sometimes wonder whether it's possible to have a central repository of compiler permutations to test and have each library reference that.
* Current CI scripts often contain hacks to workaround the time limits on Appveyor/Travis, it may be that much simpler scripts are possible here depending on what your timeouts are.

I realise you're only just getting started, and much of the above are thought for the future, in the meantime, if you need a guinea pig to test stuff on then Boost.Config is a good candidate.

**Comment by sdarwin** [comment]
> I don't see anywhere what the OS is, OK Linux, x64, but there can be differences between distros. Ditto for OS X release.

That's something to think about adding.
The left column which lists the job names and currently shows "Linux" is narrow. While the exact distro could also be shown there, many test suites use the same distro, repeatedly displaying it takes up limited screen real estate. The job name is configurable.

> Is there a way to add a status badge to the projects readme?

Yes. The badge markdown is available on the settings page in the Drone UI.

> What compilers are currently available on the server? I notice that Config really should be testing gcc/clang-10 for example.

The strategy would be to add a clang-10 job in .drone.star with packages="clang-10". That is, install the compiler from the job configuration.
 
> Currently available CI has a preponderance of x64 testing. For numerical software (Math, Multiprecision, Random) this has been bugging me as a big hole in our current testing. Is this a gap you might be prepared to try and fill?
> Commercial compilers such as Intel C++ are unusable on Travis despite having a free licence for open source projects, is this something you might be able to make available? There are others of course: Oracle on Solaris, IBM on AIX/Linux and so on.

You are proposing an expanded set of hardware to run tests on. Drone supports connecting various runners or agents to the server. It's definitely possible from a technical perspective to have an agent on different hardware.  If you had access to specialized servers currently, we could install an agent and route jobs with labels. https://docs.drone.io/pipeline/docker/syntax/routing/

> Maintaining separate CI scripts for each Boost library is a pain, and results in somewhat patchy CI testing, I sometimes wonder whether it's possible to have a central repository of compiler permutations to test and have each library reference that.

https://github.com/boostorg/boost-ci/blob/master/ci/drone/ is a central location for drone files, and could possibly have yet another .star file with a common set of tests.   I will add an Issue.

> Current CI scripts often contain hacks to workaround the time limits on Appveyor/Travis, it may be that much simpler scripts are possible here depending on what your timeouts are.

The default pipeline timeout is 60 minutes. A system admin can increase the pipeline timeout by changing the Timeout dropdown on the repository settings screen, and clicking Save. https://discourse.drone.io/t/how-to-increase-pipeline-timeout/6120

**Comment by jzmaddock** [comment]
>>I don't see anywhere what the OS is, OK Linux, x64, but there can be differences between distros. Ditto for OS X release.

>That's something to think about adding.
The left column which lists the job names and currently shows "Linux" is narrow. While the exact distro could also be shown there, many test suites use the same distro, repeatedly displaying it takes up limited screen real estate. The job name is configurable.

Thanks, I spotted a "ubuntu" lurking somewhere in the details.  However, the reason this matters is in figuring out what packages are available.  For example, I tried to add gcc-10 to the Boost.Config tests, but the package wasn't found: https://drone.cpp.al/boostorg/config/5/14/2

I noticed an undocumented llvm_os="xenial" being used elsewhere, so on the off chance that might set the OS version, I've tried adding llvm_os="focal", but it would be better if this was documented.

Likewise the MacOS tests have an `xcode_version="10.2"` option which is reasonably obvious, but less obvious is what legal values are supported.

>Yes. The badge markdown is available on the settings page in the Drone UI.

Got it, thanks!

>You are proposing an expanded set of hardware to run tests on. Drone supports connecting various runners or agents to the server. It's definitely possible from a technical perspective to have an agent on different hardware. If you had access to specialized servers currently, we could install an agent and route jobs with labels. https://docs.drone.io/pipeline/docker/syntax/routing/

Unfortunately I don't have such hardware here, it was just a nagging feeling that we currently have a blind spot in our testing.

**Comment by sdarwin** [comment]
Hi @jzmaddock,

Your comments are extremely helpful!  I've added more documentation to answer the questions.  
https://github.com/CPPAlliance/drone-ci/blob/master/docs/drone-ci.md  

gcc-10 requires Ubuntu 20.04.  Set image="cppalliance/droneubuntu2004:1"

**Comment by jzmaddock** [comment]
> gcc-10 requires Ubuntu 20.04. Set image="cppalliance/droneubuntu2004:1"

Thanks, after a bit more blundering I have that working - much appreciated!
