### ISSUE TITLE
FreeBSD compilers

### ISSUE THREAD

**Issue by Flamefire** [CPPAlliance/drone-ci#10]
Which compilers are installed on FreeBSD? g++-11 seems to not be found

**Comment by sdarwin** [comment]
Good idea, I will see about installing additional compilers. Right now it's "g++11" without the hyphen.

**Comment by Flamefire** [comment]
> Right now it's "g++11" without the hyphen.

What? Is that something FreeBSD specific? On every other system it has the hyphen and the scripts expect that too

**Comment by sdarwin** [comment]
Based on a brief testing, the boost-ci scripts were able to work correctly using "g++11". It didn't crash the jobs. Just use  "g++11" as the compiler in .drone.star.   
If you are referring to other CI, such as appveyor, gha, then maybe you are right, they must be adjusted.

**Comment by sdarwin** [comment]
I spoke too soon about the naming convention.  It looks like b2 breaks when attempting to run "g++10", etc.  Some magic had allowed it to work with the default g++.  In any case, the solution is to create symbolic links for all installed compilers, adding a hyphen, so it resembles Linux.   This has been done on the server side. The result is that g++-10 exists, and acts like other operating systems.  

More details in https://github.com/CPPAlliance/drone-ci/blob/master/docs/drone-ci.md .  List of compilers: 
```
g++-8 g++-9 g++-10 g++-11  
clang++-10 clang++-11 clang++-12 clang++-13 clang++-14 clang++-15  
```

BTW - scripts to install drone agents on servers:  https://github.com/CPPAlliance/ansible-dronerunner

**Comment by Flamefire** [comment]
Thanks!
