### ISSUE TITLE
FreeBSD: GCC 11 not working

### ISSUE THREAD

**Issue by Flamefire** [CPPAlliance/drone-ci#12]
Trying to build Boost.Locale with GCC 11 yields

`ld-elf.so.1: /usr/local/lib/gcc10/libstdc++.so.6: version GLIBCXX_3.4.29 required by /tmp/drone-x04FKooQ7tOKERiA/drone/boost-root/bin.v2/libs/locale/build/gcc-11/release/cxxstd-11-iso/threadapi-pthread/threading-multi/visibility-hidden/libboost_locale.so.1.81.0 not found`

**Comment by sdarwin** [comment]
This was mentioned in https://github.com/CPPAlliance/drone-ci/blob/master/docs/drone-ci.md

"Notice the linkflags used with gcc:  

```
  freebsd_cxx("gcc 11 freebsd", "g++-11", buildtype="boost", buildscript="drone", freebsd_version="13.1", environment={'B2_TOOLSET': 'gcc-11', 'B2_CXXSTD': '17,20', 'B2_LINKFLAGS': '-Wl,-rpath=/usr/local/lib/gcc11'}, globalenv=globalenv),
  freebsd_cxx("clang 14 freebsd", "clang++-14", buildtype="boost", buildscript="drone", freebsd_version="13.1", environment={'B2_TOOLSET': 'clang-14', 'B2_CXXSTD': '17,20'}, globalenv=globalenv),
```

**Comment by Flamefire** [comment]
Hm, I wonder if this is an issue with the paths in LD_LIBRARY_PATH or so as I thought it should "just work"

**Comment by sdarwin** [comment]
If installing _multiple gcc versions_ on freebsd it displays this message:

```
To ensure binaries built with this toolchain find appropriate versions
of the necessary run-time libraries, you may want to link using

  -Wl,-rpath=/usr/local/lib/gcc11
```

**Comment by Flamefire** [comment]
Ok :/ This might be something we may wrap in a function too. I'll test that in my repo

**Comment by Flamefire** [comment]
I tried with GCC and getting segfaults. This seems to be due to GCCs [libstdc++ calling into libcxxrt.so](https://forums.freebsd.org/threads/when-libstdc-attempts-to-interact-with-libcxxrt-so-1-bad-things-happen.56542/) which then segfaults:

```
==1871== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==1871==  Bad permissions for mapped region at address 0x5A55D48
==1871==    at 0x5A55D48: ??? (in /lib/libcxxrt.so.1)
==1871==    by 0x4FE7145: bool std::has_facet<std::ctype<char> >(std::locale const&) (in /usr/local/lib/gcc11/libstdc++.so.6.0.29)
==1871==    by 0x4FD8C04: std::basic_ios<char, std::char_traits<char> >::_M_cache_locale(std::locale const&) (in /usr/local/lib/gcc11/libstdc++.so.6.0.29)
==1871==    by 0x4FD90A0: std::basic_ios<char, std::char_traits<char> >::init(std::basic_streambuf<char, std::char_traits<char> >*) (in /usr/local/lib/gcc11/libstdc++.so.6.0.29)
==1871==    by 0x4F7345B: std::ios_base::Init::Init() (in /usr/local/lib/gcc11/libstdc++.so.6.0.29)
==1871==    by 0x4114E3: __static_initialization_and_destruction_0(int, int) (iostream:74)
==1871==    by 0x41150D: _GLOBAL__sub_I_main (hello.cpp:35)
```

This is from a FreeBSD VirtualBox. Haven't been able to get Boost.Locale working at all with GCC, clang works.
