### ISSUE TITLE
upgrade Xcode on unorderedmac1.cpp.al

### ISSUE THREAD

**Issue by sdarwin** [CPPAlliance/drone-ci#14]
> I guess this can be fixed by upgrading Xcode, but don't know how to do that.

@joaquintides 

I will work on it, after the holidays.

**Comment by joaquintides** [comment]
Hi Sam, thank you!

**Comment by sdarwin** [comment]
Hi @joaquintides  ,

I have installed the latest Xcode 14.2.   However, the benchmark machine unorderedmac1.cpp.al is running this operating system: 

```
sw_vers
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79
```
Notice, 12.4.   https://xcodereleases.com/  indicates the minimum recommended OS version for Xcode 14.2 is 12.5 . Which means there could be incompatibilities.  

When upgrading the OS there are problems.   MacOS is not a server-grade operating system like Linux.   It's buggy. A solution could be to replace the entire machine if that is required.

You were using Xcode 13.4.1 before. 

13.4.1 was released in June 2022 so that is pretty new.   Less than 1 year old.   

- Is 13.4.1 already obsolete for unordered benchmark testing?  Are you fairly sure that you require 14.2?
- Try changing the github actions configuration file from 13.4.1 to 14.2,  see if it crashes due to version incompatibilities.

**Comment by joaquintides** [comment]
Upraged to XCode 14.2 but the problem persists:
https://github.com/boostorg/boost_unordered_benchmarks/actions/runs/3836427844/jobs/6530591966

**Comment by sdarwin** [comment]
Investigating this issue back in January, the missing header files aren't yet included in Xcode.  A likely solution is to use a different compiler such as gcc, another operating system, or wait for a future release of Xcode.

Searching files in the xcode 14.2 folder:
43184:Xcode-14.2.app cppal$ find . -name "*memory_resource.cpp" 
43184:Xcode-14.2.app cppal$ find . -name "*memory_resource.h" 
43184:Xcode-14.2.app cppal$ 

References:
https://reviews.llvm.org/D89057
https://quuxplusone.github.io/blog/2018/06/05/libcpp-memory-resource/

**Comment by joaquintides** [comment]
Thanks for your investigation!
