### ISSUE TITLE
Errors with XCode 9.4.1

### ISSUE THREAD

**Issue by Flamefire** [CPPAlliance/drone-ci#15]
In my testing I can't get it working. Either ([when using no explicit stdlib](https://drone.cpp.al/boostorg/boost-ci/341/38/2)) it fails due to a missing `std::nullptr_t`: 

And shows a warning:
> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]

But using libc++ [yields](https://drone.cpp.al/boostorg/boost-ci/340/38/2): 

> clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)

Any idea how to fix that? Maybe in Boost.Config?

**Comment by sdarwin** [comment]
A version of `b2` that was released between Jun 30 and July 30, 2022 broke XCode builds.

Refer to https://github.com/bfgroup/b2/issues/200 , and the original slack thread where it may be more readable.

**Comment by Flamefire** [comment]
Ok anyway it isn't an issue with the drone image then. Also Boost.Config has a fix now. So closing
