### ISSUE TITLE
example drone files

### ISSUE THREAD

**Issue by sdarwin** [CPPAlliance/drone-ci#2]
1. In https://github.com/boostorg/boost-ci, provide a general example by converting .travis.yml to .drone.star.    
2. Possibly add a similar file in the /ci/drone folder, to enable further automation methods.

**Comment by jzmaddock** [comment]
I think some examples would help a  great deal ;)

With regard to the UUID's and the job numbers in the "name" field, all these numeric ID's are fine for machine generated files, but once we start editing these files by hand - and we will given that the compiler list needs regular updating - they're a right pain :(

Am I correct in thinking that they're strictly optional and the UUID's are just a way to refer to specific jobs in scripts?

If so wonder if this could be improved - maybe automatically set the UUID to the hash of the job name and display it at the start of each run so we can look it up if required?

As guess my beef is that in concentrating on being able to emulate Travis scripts, we've ended up with (perhaps) unnecessarily complex examples to learn from.  So, as well as some porting examples, actually, some really simple minimalist examples would maybe be just as useful!

Keep up the good work, John.

**Comment by sdarwin** [comment]
> Am I correct in thinking that they're strictly optional and the UUID's are just a way to refer to specific jobs in scripts?

Correct.  They are optional, and if the scripts don't use them, they can be omitted.   Or, you could have conditional logic making decisions based on the job name instead of the uuid, and that's another way to get rid of the uuid.   The reason for not doing that initially was because the names are long and have spaces.

> automatically set the UUID to the hash of the job name 

If the name is changed, the hash changes, then the job scripts themselves must be modified. It probably can't be automated to that extent.

Here's a proposal.  For each project, go into the .drone directory and check for a UUID.
```
cd .drone
grep UUID *
```
If it's missing, remove UUID everywhere.

The purpose of having DRONE_JOB_UUID was that some repos share logic between multiple jobs, the same "before-install" section for example, and these could be grouped together by their DRONE_JOB_UUID.

**Comment by jzmaddock** [comment]
Thanks Sam, a quick grep suggests that Boost.Outcome is the only library that uses the UUID's.

**Comment by sdarwin** [comment]
This issue was to create "example drone files"   That has been done, refer to boost-ci:    
https://github.com/boostorg/boost-ci/tree/master/.drone  
https://github.com/boostorg/boost-ci/blob/master/.drone.star
