### ISSUE TITLE
Drone note triggered after PR merge

### ISSUE THREAD

**Issue by joaquintides** [CPPAlliance/drone-ci#3]
Not sure this is a problem or by design, but accepting the following PR:

https://github.com/boostorg/multi_index/pull/40

has not triggered Drone on my repo (it has triggered AppVeyor, for instance). Is this normal?

**Comment by sdarwin** [comment]
Hi @joaquintides,
It is a puzzle.  Maybe because the change only involved a "hidden" directory or the drone files themselves.
Submitted new PR: https://github.com/boostorg/multi_index/pull/41, and it ran:
"continuous-integration/drone/pr Pending — Build is running"

**Comment by sdarwin** [comment]
Oh. Of course! The reason is obvious.  :-)   
Another developer had requested I add "[ci skip]" to pull requests, because Travis is backed up and shouldn't run additional jobs.   Since then, the script I have been using has automatically added "[ci skip]" to all commits.

**Comment by joaquintides** [comment]
Obvious enough, thank you :-) OTOH AppVeyor seems not to honor [ci skip].
