### ISSUE TITLE
Is it possible to run ASAN compiled programs?

### ISSUE THREAD

**Issue by jzmaddock** [CPPAlliance/drone-ci#4]
See: https://drone.cpp.al/boostorg/multiprecision/76/134/2

**Comment by jzmaddock** [comment]
Never mind, got this working on GHA.

**Comment by sdarwin** [comment]
> Is it possible to run ASAN 

Yes. 
Step 1: Have the administrator set the repo to "Trusted".  I have now done this.  (and for a few other repos as well).
Step 2: Add privileged=True to the job in .drone.star.
