### ISSUE TITLE
Update images?

### ISSUE THREAD

**Issue by jzmaddock** [CPPAlliance/drone-ci#8]
Any plans to support Ubuntu-22.04 and the latest XCode versions?

Thanks!

**Comment by sdarwin** [comment]
Hi John,
Ubuntu-22.04 is already supported.  Just modified the docs to display that.  
Latest XCode - yes, I need to build new runners for those versions.   Will work on it.

**Comment by sdarwin** [comment]
New OSX servers installed and running at macminivault.com .  xcode versions available 12.5 12.5.1 13.0 13.1 13.2 13.2.1 13.3 13.3.1 13.4 13.4.1

**Comment by jzmaddock** [comment]
Thank you!
